import Obj from "./../../../src/components/editable-item.vue";
export default Obj;
/* Automatic generated by hsk-garen */
// import Obj from "./../../../node_modules/@hasaki-ui/hsk-teemo/lib/component/editable-item.js";
// export default Obj;
